services:
  - type: web
    name: object-hunt
    env: node
    plan: free
    buildCommand: npm install && npm run heroku-postbuild
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18 